services:
  ai:
    build: ./ai
    depends_on:
      - backend
    volumes:
      - ./ai/src:/app/src

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
    env_file:
      - ./backend/src/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
